"""Single-case PDF report (PRD 7.3 stretch).

Built server-side with ReportLab rather than from the browser's print
dialog, for one reason: the export is meant to be the artifact a reviewer
attaches to a case file, so it has to contain exactly the fields the case
was decided on -- including the ones the UI collapses or truncates -- and
be reproducible from the API alone, without a browser in the loop.

The document deliberately reproduces the demo-mode notice: a PDF outlives
the page it came from, and a fraud verdict sheet with no provenance on it
is the kind of thing that gets mistaken for a real one.
"""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.models import Transaction

AGENT_LABELS = {
    "anomaly_agent": "Anomaly (ML)",
    "context_agent": "Context (LLM)",
    "policy_agent": "Policy (rules)",
}
AGENT_ORDER = ["anomaly_agent", "context_agent", "policy_agent"]

VERDICT_COLORS = {
    "allow": colors.HexColor("#1a7f37"),
    "escalate": colors.HexColor("#bf8700"),
    "block": colors.HexColor("#b3261e"),
}


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], fontSize=16, alignment=TA_LEFT, spaceAfter=2),
        "subtle": ParagraphStyle("subtle", parent=base["Normal"], fontSize=8, textColor=colors.grey),
        "heading": ParagraphStyle("heading", parent=base["Heading2"], fontSize=11, spaceBefore=10, spaceAfter=4),
        "body": ParagraphStyle("body", parent=base["Normal"], fontSize=9, leading=12),
        "cell": ParagraphStyle("cell", parent=base["Normal"], fontSize=8.5, leading=11),
    }


def _kv_table(rows: list[tuple[str, str]], style) -> Table:
    table = Table(
        [[Paragraph(f"<b>{k}</b>", style), Paragraph(v, style)] for k, v in rows],
        colWidths=[45 * mm, 120 * mm],
        hAlign="LEFT",
    )
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.HexColor("#e5e5e5")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (0, -1), 0),
            ]
        )
    )
    return table


def build_case_report(txn: Transaction) -> bytes:
    """Render one transaction's full case file -- inputs, every agent
    opinion, the coordinator's reasoning, and any human overrides -- as PDF
    bytes.
    """
    style = _styles()
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"Fraud case {txn.id[:8]}",
        author="Fraud Investigation Squad",
    )

    review = txn.review_result
    verdict = review.final_verdict if review else "no verdict recorded"
    verdict_color = VERDICT_COLORS.get(verdict, colors.black)

    story = [
        Paragraph(f"Case {txn.id[:8]}", style["title"]),
        Paragraph(
            f'Verdict: <font color="{verdict_color.hexval()}"><b>{verdict.upper()}</b></font>',
            style["body"],
        ),
        Spacer(1, 4),
        Paragraph(
            "DEMO MODE -- synthetic data only. This report is generated by a portfolio "
            "project, not a licensed fraud system, and describes no real person or payment.",
            style["subtle"],
        ),
        Spacer(1, 8),
        Paragraph("Transaction", style["heading"]),
        _kv_table(
            [
                ("Case ID", txn.id),
                ("User", txn.user_id),
                ("Amount", f"${txn.amount:,.2f}"),
                ("Type", txn.transaction_type),
                (
                    "Origin balance",
                    f"${txn.origin_balance_before:,.2f} &rarr; ${txn.origin_balance_after:,.2f}",
                ),
                ("Location", txn.location_country),
                ("Occurred at", txn.occurred_at.strftime("%Y-%m-%d %H:%M:%S")),
            ]
            + (
                [("Ground truth (eval data only)", "fraud" if txn.is_fraud_ground_truth else "legitimate")]
                if txn.is_fraud_ground_truth is not None
                else []
            ),
            style["cell"],
        ),
        Paragraph("Agent opinions", style["heading"]),
    ]

    opinions = sorted(
        txn.opinions,
        key=lambda o: AGENT_ORDER.index(o.agent_name) if o.agent_name in AGENT_ORDER else len(AGENT_ORDER),
    )
    if opinions:
        opinion_rows = [
            [
                Paragraph("<b>Agent</b>", style["cell"]),
                Paragraph("<b>Score</b>", style["cell"]),
                Paragraph("<b>Flag</b>", style["cell"]),
                Paragraph("<b>Reasoning</b>", style["cell"]),
            ]
        ] + [
            [
                Paragraph(AGENT_LABELS.get(o.agent_name, o.agent_name), style["cell"]),
                Paragraph(f"{o.score:.2f}", style["cell"]),
                Paragraph("flagged" if o.flag else "clear", style["cell"]),
                Paragraph(o.reasoning, style["cell"]),
            ]
            for o in opinions
        ]
        table = Table(opinion_rows, colWidths=[28 * mm, 14 * mm, 16 * mm, 107 * mm], hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f5f5f5")),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e0e0e0")),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No agent opinions recorded for this transaction.", style["body"]))

    if review:
        story += [
            Paragraph("Coordinator reasoning", style["heading"]),
            Paragraph(review.coordinator_reasoning, style["body"]),
        ]
        if review.human_reviews:
            story.append(Paragraph("Reviewer overrides", style["heading"]))
            for human_review in sorted(review.human_reviews, key=lambda r: r.reviewed_at):
                story.append(
                    KeepTogether(
                        [
                            Paragraph(
                                f"<b>{human_review.decision}</b> by {human_review.reviewer_id} "
                                f"on {human_review.reviewed_at.strftime('%Y-%m-%d %H:%M:%S')}",
                                style["body"],
                            ),
                            Paragraph(human_review.note, style["body"]),
                            Spacer(1, 6),
                        ]
                    )
                )

    doc.build(story)
    return buffer.getvalue()
